#!/usr/bin/env bash

set -euo pipefail

bail() {
    echo "Usage: configure_build <build_type(Release or Debug)>" >&2
    exit 1
}

mkdir -p build

build_type=Debug
if [[ $# -eq 1 ]]; then
    build_type="${1}"
fi
if [[ ! "${build_type}" =~ ^(Debug|Release)$ ]]; then
    bail
fi

cmake -S . -B build \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_OSX_SYSROOT="$(xcrun --show-sdk-path)" \
    -DCMAKE_BUILD_TYPE="${build_type}"
